"""change

Revision ID: 59c6634988c5
Revises: 5e3040523203
Create Date: 2025-05-22 19:46:13.901221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c6634988c5'
down_revision: Union[str, None] = '5e3040523203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layerstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('layer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adds', sa.Integer(), nullable=False),
    sa.Column('updates', sa.Integer(), nullable=False),
    sa.Column('deletes', sa.Integer(), nullable=False),
    sa.Column('kilometers', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('editevent', sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('editevent', sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('editevent', 'layer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('editevent', 'fid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('editevent', 'field',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('editevent', 'field',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('editevent', 'fid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('editevent', 'layer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('editevent', 'extra')
    op.drop_column('editevent', 'action')
    op.drop_table('layerstat')
    # ### end Alembic commands ###
