"""baseline

Revision ID: 5e3040523203
Revises: 
Create Date: 2025-05-01 09:08:13.315077

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3040523203'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('layer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wkt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editevent')
    # ### end Alembic commands ###
